#!/usr/bin/env python3

import re
import sys

TO_ADD = """\
[Desktop Entry]
DefaultProfile=Default Profile.profile
"""
SECTION_PATTERN_RE = re.compile(r"\[Desktop Entry\]\n[\s\S]*?\n(\n|$)")

original_contents = sys.stdin.read()

if original_contents:
    print(SECTION_PATTERN_RE.sub(rf"{TO_ADD}\1", original_contents), end="")
else:
    print(TO_ADD, end="")
