#!/usr/bin/env python3

import re
import sys

TO_ADD = {
    "TerminalApplication": "kitty --single-instance",
}

SECTION_PATTERN_RE = re.compile(r"\[General\]\n[\s\S]*?\n(\n|$)")

original_contents = sys.stdin.read()

def repl(match: re.Match[str]) -> str:
    lines = match.group(0).splitlines(keepends=True)
    for idx, line in enumerate(lines):
        key, _, value = line.partition("=")
        if not value:
            continue
        new_value = TO_ADD.get(key)
        if new_value is not None:
            lines[idx] = f"{key}={TO_ADD[key]}\n"

    return f"{''.join(lines)}"


if original_contents:
    print(SECTION_PATTERN_RE.sub(repl, original_contents), end="")
else:
    lines = ["[General]\n"]
    for key, value in TO_ADD.items():
        lines.append(f"{key}={value}\n")
    print("".join(lines), end="")
