#!/usr/bin/env python3

import re
import sys

TO_ADD = """\
[General]
Config Revision=10
Days Meta Infos=30
Save Meta Infos=true
Show Full Path in Title=true
Show Menu Bar=true
Show Status Bar=true
Show Tab Bar=true
"""
SECTION_PATTERN_RE = re.compile(r"\[General\]\n[\s\S]*?\n(\n|$)")

original_contents = sys.stdin.read()

if original_contents:
    print(SECTION_PATTERN_RE.sub(rf"{TO_ADD}\1", original_contents), end="")
else:
    print(TO_ADD, end="")
